### ISSUE TITLE
utest dependency

### ISSUE THREAD

**Issue by kerimdzhanov** [felixge/node-urun#3]
Is it ok that `urun v0.0.6` depends on old version of `utest v0.0.2`? https://github.com/felixge/node-urun/blob/master/package.json#L22

**Comment by felixge** [comment]
No that seems wrong. It should only be a dev dependency. Upgrading it to a newer version would also be nice. Want to help?

**Comment by kerimdzhanov** [comment]
Yes, i would be glad.
