### ISSUE TITLE
Publilsh new release

### ISSUE THREAD

**Issue by dougwilson** [felixge/node-urun#6]
@felixge can you publish the current `master` code as a new release? I actually need the `verbose` flag :D

**Comment by felixge** [comment]
Done -> 0.0.8. Btw. if you want to use another test runner / framework for node-mysql at this point, please go for it. I'm still quite fond of the way urun/utest/etc. work, but since I'm not the one doing the work my preferences should take the back seat :)

**Comment by dougwilson** [comment]
> Done -> 0.0.8

Thanks! :sparkling_heart: 

> if you want to use another test runner / framework for node-mysql 

I may, but I have to invest time to move the tests ;) and I don't have any at the moment, haha.

With the `verbose` flag, there now, I don't have any actual need to change it :)

**Comment by felixge** [comment]
:+1:
